-- =============================================
-- 1. Representatives Management
-- =============================================

CREATE TABLE IF NOT EXISTS dental_lab_representatives (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    laboratory_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    position VARCHAR(100),
    representative_type VARCHAR(50) CHECK (representative_type IN ('delivery', 'technical', 'administrative')) DEFAULT 'delivery',
    status VARCHAR(50) CHECK (status IN ('available', 'busy', 'offline')) DEFAULT 'available',
    current_assignments INTEGER DEFAULT 0,
    max_assignments INTEGER DEFAULT 5,
    total_deliveries INTEGER DEFAULT 0,
    successful_deliveries INTEGER DEFAULT 0,
    cancelled_deliveries INTEGER DEFAULT 0,
    rating DECIMAL(3, 2) DEFAULT 0.0,
    vehicle_type VARCHAR(50),
    working_hours JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_reps_lab_id ON dental_lab_representatives(laboratory_id);

-- RPC: add_representative
CREATE OR REPLACE FUNCTION add_representative(
    p_laboratory_id UUID,
    p_user_id UUID,
    p_full_name VARCHAR,
    p_phone VARCHAR,
    p_email VARCHAR,
    p_position VARCHAR,
    p_representative_type VARCHAR,
    p_max_assignments INTEGER,
    p_working_hours JSONB
) RETURNS UUID AS $$
DECLARE
    v_id UUID;
BEGIN
    INSERT INTO dental_lab_representatives (
        laboratory_id, full_name, phone, email, position,
        representative_type, max_assignments, working_hours
    ) VALUES (
        p_laboratory_id, p_full_name, p_phone, p_email, p_position,
        p_representative_type, p_max_assignments, p_working_hours
    ) RETURNING id INTO v_id;
    
    RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: update_representative_status
CREATE OR REPLACE FUNCTION update_representative_status(
    p_representative_id UUID,
    p_new_status VARCHAR
) RETURNS VOID AS $$
BEGIN
    UPDATE dental_lab_representatives
    SET status = p_new_status, updated_at = NOW()
    WHERE id = p_representative_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =============================================
-- 2. Chat System (Lab <-> Doctor)
-- =============================================

CREATE TABLE IF NOT EXISTS lab_chat_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id UUID REFERENCES doctors(id) ON DELETE CASCADE,
    lab_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    order_id UUID REFERENCES dental_lab_orders(id) ON DELETE SET NULL,
    last_message_content TEXT,
    last_message_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lab_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT REFERENCES lab_chat_conversations(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    message_type VARCHAR(50) DEFAULT 'text', -- text, price, image, file
    message_content TEXT,
    file_url TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_chat_conv_lab ON lab_chat_conversations(lab_id);
CREATE INDEX IF NOT EXISTS idx_chat_conv_doc ON lab_chat_conversations(doctor_id);
CREATE INDEX IF NOT EXISTS idx_chat_msgs_conv ON lab_chat_messages(conversation_id);


-- RPC: get_lab_conversations
CREATE OR REPLACE FUNCTION get_lab_conversations(p_user_id UUID)
RETURNS TABLE (
    conversation_id BIGINT,
    doctor_id UUID,
    lab_id UUID,
    order_id UUID,
    last_message_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE,
    doctor_name VARCHAR,
    lab_name VARCHAR,
    order_number VARCHAR,
    unread_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        c.id,
        c.doctor_id,
        c.lab_id,
        c.order_id,
        c.last_message_date,
        c.created_at,
        d.full_name as doctor_name,
        -- Need to get lab name from somewhere, assume auth.users metadata or dental_laboratories link
        NULL::VARCHAR as lab_name, 
        o.order_number,
        (SELECT COUNT(*) FROM lab_chat_messages m WHERE m.conversation_id = c.id AND m.is_read = FALSE AND m.sender_id != p_user_id) as unread_count
    FROM lab_chat_conversations c
    LEFT JOIN doctors d ON c.doctor_id = d.id
    LEFT JOIN dental_lab_orders o ON c.order_id = o.id
    WHERE c.lab_id = p_user_id OR c.doctor_id = (SELECT id FROM doctors WHERE id = p_user_id); -- Handle both sides if needed, but primarily lab side here
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC: get_conversation_messages
CREATE OR REPLACE FUNCTION get_conversation_messages(p_conversation_id BIGINT)
RETURNS TABLE (
    message_id BIGINT,
    sender_id UUID,
    message_type VARCHAR,
    message_content TEXT,
    file_url TEXT,
    is_read BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE,
    sender_name VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        m.id,
        m.sender_id,
        m.message_type,
        m.message_content,
        m.file_url,
        m.is_read,
        m.created_at,
        -- Try to resolve sender name. This is tricky with mixed tables (auth.users vs doctors). 
        -- For display purposes, the frontend often knows "Me" vs "Them".
        'Sender'::VARCHAR as sender_name
    FROM lab_chat_messages m
    WHERE m.conversation_id = p_conversation_id
    ORDER BY m.created_at ASC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC: send_lab_message
CREATE OR REPLACE FUNCTION send_lab_message(
    p_conversation_id BIGINT,
    p_sender_id UUID,
    p_message_type VARCHAR,
    p_message_content TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO lab_chat_messages (conversation_id, sender_id, message_type, message_content)
    VALUES (p_conversation_id, p_sender_id, p_message_type, p_message_content);

    UPDATE lab_chat_conversations
    SET last_message_content = p_message_content,
        last_message_date = NOW()
    WHERE id = p_conversation_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC: mark_messages_as_read
CREATE OR REPLACE FUNCTION mark_messages_as_read(
    p_conversation_id BIGINT,
    p_user_id UUID
) RETURNS VOID AS $$
BEGIN
    UPDATE lab_chat_messages
    SET is_read = TRUE
    WHERE conversation_id = p_conversation_id
    AND sender_id != p_user_id; -- Mark messages sent by the OTHER party as read
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
