-- Create Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL, -- Assuming clinics table exists or simple int reference
    item_name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('equipment', 'consumables', 'medicines', 'instruments', 'supplies')),
    quantity INTEGER NOT NULL DEFAULT 0,
    unit_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    min_stock INTEGER NOT NULL DEFAULT 5,
    unit TEXT DEFAULT 'pcs',
    supplier_name TEXT,
    brand TEXT,
    location TEXT,
    expiry_date DATE,
    condition TEXT CHECK (condition IN ('excellent', 'good', 'fair', 'poor')),
    status TEXT GENERATED ALWAYS AS (
        CASE 
            WHEN quantity = 0 THEN 'out_of_stock'
            WHEN quantity <= min_stock THEN 'low_stock'
            WHEN expiry_date < CURRENT_DATE THEN 'expired'
            ELSE 'available' 
        END
    ) STORED,
    last_restock_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

-- Policies (Simplified for now - can be refined based on auth.uid())
-- Allow all authenticated users to read/write for now
CREATE POLICY "Enable all access for authenticated users" ON inventory
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');
