-- Check ALL tables mentioned in hooks
SELECT table_name, 
       CASE WHEN table_name IN (
           SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'
       ) THEN 'EXISTS' ELSE 'MISSING' END as status
FROM (VALUES
    ('favorites'),
    ('financial_transactions'),
    ('tasks'),
    ('suppliers'),
    ('products'),
    ('order_items'),
    ('store_orders'),
    ('store_order_items'),
    ('supplier_jobs'),
    ('supplier_expenses'),
    ('clinics'),
    ('users'),
    ('patients'),
    ('subscription_plans'),
    ('ai_logs'),
    ('appointments'),
    ('inventory'),
    ('inventory_categories'),
    ('doctor_subscriptions'),
    ('clinic_doctors'),
    ('clinic_staff'),
    ('treatments'),
    ('invoices'),
    ('lab_orders'),
    ('lab_requests'),
    ('lab_services'),
    ('lab_messages'),
    ('laboratories'),
    ('representatives'),
    ('articles'),
    ('assets'),
    ('jobs'),
    ('job_applications'),
    ('professional_profiles'),
    ('coupons'),
    ('receipts'),
    ('admin_notifications'),
    ('support_tickets'),
    ('platform_settings'),
    ('reviews'),
    ('cart_items'),
    ('addresses'),
    ('shipping_zones'),
    ('conversations'),
    ('messages'),
    ('online_consultation_requests'),
    ('payment_methods'),
    ('withdrawal_requests')
) AS t(table_name)
ORDER BY status DESC, table_name;
